"""
Train the NYCTaxi ungated residual-correction ablation.

Default command from the repo root:
  C:\\Users\\PCF\\.conda\\envs\\sds-test\\python.exe scripts\\run_nyctaxi_ungated_residual_ablation.py

This ablation removes the classifier gate from training and inference:
  prediction = base_prediction + learned_bias

It trains NYCTaxi seeds 1, 2, 3 and, when available, compares against the
latest original Hyb-STEX results produced by run_nyctaxi_drift_experiment.py.

By default, the script reads saved evs_90 labels from preprocessed_data. These
labels should be generated by createDataWithEVLabels.ipynb or
scripts/create_ev_labels.py, which estimate thresholds on the training split
and apply them unchanged to train/validation/test.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
import sys
import time
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import torch
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from run_nyctaxi_drift_experiment import (  # noqa: E402
    DEFAULT_MAIN_OPTIONS,
    EVENT_THRESHOLD_SOURCE_CHOICES,
    FLOW_NAMES,
    StandardScaler,
    add_repo_to_path,
    build_dataloaders,
    get_model_params_grouped,
    load_arrays,
    load_graph,
    parse_seed_list,
    preflight_environment,
    repo_root,
)


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        configs = yaml.load(handle, Loader=yaml.FullLoader)
    for key, value in DEFAULT_MAIN_OPTIONS.items():
        configs.setdefault(key, value)
    return configs


def init_seed(seed: int, device: str) -> None:
    torch.cuda.cudnn_enabled = False
    torch.backends.cudnn.deterministic = True
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if device == "cuda":
        torch.cuda.manual_seed(seed)


def build_run_args(
    configs: dict[str, Any],
    data_dir: Path,
    seed: int,
    device: str,
    max_epochs: int | None,
) -> argparse.Namespace:
    run_configs = dict(configs)
    run_configs["seed"] = seed
    run_configs["mode"] = "train"
    run_configs["device"] = device
    run_configs["data_dir"] = str(data_dir)
    run_configs["dataset"] = "NYCTaxi"
    run_configs["graph_file"] = str(data_dir / "NYCTaxi" / "adj_mx.npz")
    run_configs["best_path"] = None
    run_configs["debug"] = False
    run_configs["phase3_mode"] = "ungated_residual"
    run_configs["comment"] = "nyctaxi_ungated_residual"
    run_configs["experimentName"] = f"nyctaxi_ungated_residual_seed={seed}"
    if max_epochs is not None:
        run_configs["epochs"] = max_epochs
        run_configs["num_epochs"] = max_epochs
    return argparse.Namespace(**run_configs)


def build_optimizer(model: torch.nn.Module, lr: float) -> torch.optim.Optimizer:
    pred_params, classifier_params, bias_params = get_model_params_grouped(model)
    return torch.optim.Adam(
        [
            {
                "params": pred_params,
                "lr": lr,
                "eps": 1.0e-8,
                "weight_decay": 0,
                "amsgrad": False,
            },
            {
                "params": classifier_params,
                "lr": lr,
                "eps": 1.0e-8,
                "weight_decay": 0,
                "amsgrad": True,
            },
            {
                "params": bias_params,
                "lr": lr,
                "eps": 1.0e-8,
                "weight_decay": 1.0e-8,
                "amsgrad": True,
            },
        ]
    )


def set_trainable(params_to_train: list[torch.nn.Parameter], params_to_freeze: list[torch.nn.Parameter]) -> None:
    for param in params_to_train:
        param.requires_grad = True
    for param in params_to_freeze:
        param.requires_grad = False


def masked_mae_tensor(pred: torch.Tensor, true: torch.Tensor, mask_value: float = 5.0) -> torch.Tensor:
    mask = true > mask_value
    if not torch.any(mask):
        return torch.zeros((), device=pred.device, dtype=pred.dtype)
    return torch.mean(torch.abs(true[mask] - pred[mask]))


def weighted_mae_loss(
    pred_scaled: torch.Tensor,
    true_scaled: torch.Tensor,
    scaler: StandardScaler,
    yita: float,
) -> torch.Tensor:
    pred = scaler.inverse_transform(pred_scaled)
    true = scaler.inverse_transform(true_scaled)
    return (
        yita * masked_mae_tensor(pred[..., 0], true[..., 0])
        + (1.0 - yita) * masked_mae_tensor(pred[..., 1], true[..., 1])
    )


def predict_scaled(model: torch.nn.Module, data: torch.Tensor, graph: torch.Tensor, mode: str) -> torch.Tensor:
    repr1, _ = model(data, graph)
    base = model.mlp(repr1)
    if mode == "base":
        return base
    if mode == "residual":
        return base + model.get_bias(repr1)
    raise ValueError(f"Unknown prediction mode: {mode}")


def evaluate_loss(
    model: torch.nn.Module,
    dataloader: torch.utils.data.DataLoader,
    graph: torch.Tensor,
    scaler: StandardScaler,
    yita: float,
    mode: str,
) -> float:
    model.eval()
    losses: list[float] = []
    with torch.no_grad():
        for data, target, _, _ in dataloader:
            pred = predict_scaled(model, data, graph, mode)
            loss = weighted_mae_loss(pred, target, scaler, yita)
            losses.append(float(loss.item()))
    return float(np.mean(losses))


def train_epoch(
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    dataloader: torch.utils.data.DataLoader,
    graph: torch.Tensor,
    scaler: StandardScaler,
    yita: float,
    mode: str,
    grad_norm: bool,
    max_grad_norm: float,
) -> float:
    model.train()
    losses: list[float] = []
    for data, target, _, _ in dataloader:
        optimizer.zero_grad()
        pred = predict_scaled(model, data, graph, mode)
        loss = weighted_mae_loss(pred, target, scaler, yita)
        if torch.isnan(loss):
            raise RuntimeError("NaN loss encountered.")
        loss.backward()
        if grad_norm:
            torch.nn.utils.clip_grad_norm_(
                [param for param in model.parameters() if param.requires_grad],
                max_grad_norm,
            )
        optimizer.step()
        losses.append(float(loss.item()))
    return float(np.mean(losses))


def train_component(
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    dataloaders: dict[str, Any],
    graph: torch.Tensor,
    scaler: StandardScaler,
    args: argparse.Namespace,
    params_to_train: list[torch.nn.Parameter],
    params_to_freeze: list[torch.nn.Parameter],
    mode: str,
    phase_name: str,
    patience: int,
    checkpoint_dir: Path,
) -> dict[str, Any]:
    set_trainable(params_to_train, params_to_freeze)
    best_loss = math.inf
    best_epoch = 0
    not_improved = 0
    start_time = time.time()
    best_path = checkpoint_dir / f"best_model_{phase_name}.pth"
    val_loader = dataloaders["val"] if dataloaders["val"] is not None else dataloaders["test"]

    print(f"\n--- {phase_name}: train mode={mode} ---")
    for epoch in range(1, int(args.epochs) + 1):
        train_loss = train_epoch(
            model=model,
            optimizer=optimizer,
            dataloader=dataloaders["train"],
            graph=graph,
            scaler=scaler,
            yita=float(args.yita),
            mode=mode,
            grad_norm=bool(args.grad_norm),
            max_grad_norm=float(args.max_grad_norm),
        )
        val_loss = evaluate_loss(model, val_loader, graph, scaler, float(args.yita), mode)
        print(f"{phase_name} epoch={epoch} train_loss={train_loss:.5f} val_loss={val_loss:.5f}")

        if val_loss < best_loss:
            best_loss = val_loss
            best_epoch = epoch
            not_improved = 0
            torch.save(
                {
                    "epoch": epoch,
                    "model": model.state_dict(),
                    "optimizer": optimizer.state_dict(),
                },
                best_path,
            )
        else:
            not_improved += 1

        if bool(args.early_stop) and not_improved == patience:
            print(f"{phase_name}: validation did not improve for {patience} epochs; stopping.")
            break

    state = torch.load(best_path, map_location=torch.device(args.device))
    model.load_state_dict(state["model"])
    elapsed_min = (time.time() - start_time) / 60.0
    print(f"{phase_name}: best_val_loss={best_loss:.5f} best_epoch={best_epoch} time_min={elapsed_min:.2f}")
    return {
        "phase": phase_name,
        "best_val_loss": float(best_loss),
        "best_val_epoch": int(best_epoch),
        "checkpoint": str(best_path.resolve()),
    }


def mae_value(pred: torch.Tensor, true: torch.Tensor, mask_value: float = 5.0) -> float:
    mask = true > mask_value
    if not torch.any(mask):
        return float("nan")
    return float(torch.mean(torch.abs(true[mask] - pred[mask])).item())


def eee_value(pred: torch.Tensor, true: torch.Tensor, evs: torch.Tensor) -> float:
    mask = evs == 1
    if not torch.any(mask):
        return float("nan")
    return float(torch.mean(torch.abs(true[mask] - pred[mask])).item())


def collect_outputs(
    model: torch.nn.Module,
    dataloader: torch.utils.data.DataLoader,
    graph: torch.Tensor,
    scaler: StandardScaler,
) -> dict[str, torch.Tensor]:
    model.eval()
    collected: dict[str, list[torch.Tensor]] = {"true": [], "evs": [], "base": [], "residual": []}
    with torch.no_grad():
        for data, target, evs, _ in dataloader:
            repr1, _ = model(data, graph)
            base = model.mlp(repr1)
            residual = base + model.get_bias(repr1)
            collected["true"].append(target)
            collected["evs"].append(evs)
            collected["base"].append(base)
            collected["residual"].append(residual)
    return {
        "true": scaler.inverse_transform(torch.cat(collected["true"], dim=0)),
        "evs": torch.cat(collected["evs"], dim=0),
        "base": scaler.inverse_transform(torch.cat(collected["base"], dim=0)),
        "residual": scaler.inverse_transform(torch.cat(collected["residual"], dim=0)),
    }


def evaluate_model(
    model: torch.nn.Module,
    dataloader: torch.utils.data.DataLoader,
    graph: torch.Tensor,
    scaler: StandardScaler,
    seed: int,
    phase_results: list[dict[str, Any]],
    log_dir: Path,
) -> list[dict[str, Any]]:
    outputs = collect_outputs(model, dataloader, graph, scaler)
    rows: list[dict[str, Any]] = []
    final_phase = phase_results[-1]
    for flow_index, flow_name in enumerate(FLOW_NAMES):
        true = outputs["true"][..., flow_index]
        evs = outputs["evs"][..., flow_index]
        base = outputs["base"][..., flow_index]
        residual = outputs["residual"][..., flow_index]
        rows.append(
            {
                "variant": "ungated_residual",
                "seed": seed,
                "flow": flow_name,
                "base_mae": mae_value(base, true),
                "base_eee": eee_value(base, true, evs),
                "residual_mae": mae_value(residual, true),
                "residual_eee": eee_value(residual, true, evs),
                "event_prevalence": float(evs.detach().cpu().numpy().mean()),
                "best_val_loss": float(final_phase["best_val_loss"]),
                "best_val_epoch": int(final_phase["best_val_epoch"]),
                "checkpoint": str(final_phase["checkpoint"]),
                "log_dir": str(log_dir.resolve()),
                "phase_results": json.dumps(phase_results),
            }
        )
    return rows


def run_one(
    configs: dict[str, Any],
    data_dir: Path,
    output_dir: Path,
    seed: int,
    device: str,
    event_percentile: float,
    event_threshold_source: str,
    max_epochs: int | None,
) -> list[dict[str, Any]]:
    from model.models import STSSL

    init_seed(seed, device)
    arrays = load_arrays(data_dir, event_percentile, event_threshold_source)
    dataloaders, scaler = build_dataloaders(
        arrays,
        batch_size=int(configs["batch_size"]),
        test_batch_size=int(configs["test_batch_size"]),
        device=device,
    )
    args = build_run_args(configs, data_dir, seed, device, max_epochs)
    graph = load_graph(Path(args.graph_file), device)
    args.num_nodes = len(graph)
    args.ipe = len(dataloaders["train"])

    model = STSSL(args).to(device)
    optimizer = build_optimizer(model, float(args.lr_init))
    pred_params, classifier_params, bias_params = get_model_params_grouped(model)

    checkpoint_dir = output_dir / "checkpoints" / f"seed_{seed}"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    phase_results: list[dict[str, Any]] = []
    phase_results.append(
        train_component(
            model=model,
            optimizer=optimizer,
            dataloaders=dataloaders,
            graph=graph,
            scaler=scaler,
            args=args,
            params_to_train=pred_params,
            params_to_freeze=classifier_params + bias_params,
            mode="base",
            phase_name="base_pretrain",
            patience=30,
            checkpoint_dir=checkpoint_dir,
        )
    )
    phase_results.append(
        train_component(
            model=model,
            optimizer=optimizer,
            dataloaders=dataloaders,
            graph=graph,
            scaler=scaler,
            args=args,
            params_to_train=pred_params + bias_params,
            params_to_freeze=classifier_params,
            mode="residual",
            phase_name="residual_joint",
            patience=30,
            checkpoint_dir=checkpoint_dir,
        )
    )
    phase_results.append(
        train_component(
            model=model,
            optimizer=optimizer,
            dataloaders=dataloaders,
            graph=graph,
            scaler=scaler,
            args=args,
            params_to_train=bias_params,
            params_to_freeze=pred_params + classifier_params,
            mode="residual",
            phase_name="residual_bias_finetune",
            patience=30,
            checkpoint_dir=checkpoint_dir,
        )
    )
    rows = evaluate_model(
        model=model,
        dataloader=dataloaders["test"],
        graph=graph,
        scaler=scaler,
        seed=seed,
        phase_results=phase_results,
        log_dir=checkpoint_dir,
    )

    del model, optimizer, graph, dataloaders
    if device == "cuda":
        torch.cuda.empty_cache()
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def summarize(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[str(row["flow"])].append(row)
    summary: list[dict[str, Any]] = []
    for flow, group in sorted(grouped.items()):
        item: dict[str, Any] = {"variant": "ungated_residual", "flow": flow, "n": len(group)}
        for metric in ("base_mae", "base_eee", "residual_mae", "residual_eee"):
            values = np.asarray([float(row[metric]) for row in group], dtype=np.float64)
            item[f"{metric}_mean"] = float(np.nanmean(values))
            item[f"{metric}_std"] = float(np.nanstd(values, ddof=1)) if len(values) > 1 else 0.0
        summary.append(item)
    return summary


def find_latest_baseline(root: Path) -> Path | None:
    candidates = sorted(
        (root / "nyctaxi_drift_results").glob("*/results.csv"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def read_csv_dicts(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def build_comparison(rows: list[dict[str, Any]], baseline_path: Path | None) -> list[dict[str, Any]]:
    if baseline_path is None or not baseline_path.is_file():
        return []
    baseline_rows = read_csv_dicts(baseline_path)
    original_by_key = {
        (int(row["seed"]), row["flow"]): row
        for row in baseline_rows
        if row.get("phase3_mode") == "original"
    }
    comparison: list[dict[str, Any]] = []
    for row in rows:
        key = (int(row["seed"]), str(row["flow"]))
        baseline = original_by_key.get(key)
        if baseline is None:
            continue
        hyb_mae = float(baseline["soft_mae"])
        hyb_eee = float(baseline["soft_eee"])
        residual_mae = float(row["residual_mae"])
        residual_eee = float(row["residual_eee"])
        comparison.append(
            {
                "seed": row["seed"],
                "flow": row["flow"],
                "hybstex_soft_mae": hyb_mae,
                "ungated_residual_mae": residual_mae,
                "delta_mae_ungated_minus_hybstex": residual_mae - hyb_mae,
                "hybstex_soft_eee": hyb_eee,
                "ungated_residual_eee": residual_eee,
                "delta_eee_ungated_minus_hybstex": residual_eee - hyb_eee,
                "hybstex_f1_tuned": float(baseline["test_f1_tuned"]),
            }
        )
    return comparison


def summarize_comparison(comparison: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in comparison:
        grouped[str(row["flow"])].append(row)
    summary: list[dict[str, Any]] = []
    for flow, group in sorted(grouped.items()):
        item: dict[str, Any] = {"flow": flow, "n": len(group)}
        for metric in ("delta_mae_ungated_minus_hybstex", "delta_eee_ungated_minus_hybstex"):
            values = np.asarray([float(row[metric]) for row in group], dtype=np.float64)
            item[f"{metric}_mean"] = float(np.nanmean(values))
            item[f"{metric}_std"] = float(np.nanstd(values, ddof=1)) if len(values) > 1 else 0.0
        summary.append(item)
    return summary


def fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def markdown_table(rows: list[dict[str, Any]], columns: list[str]) -> str:
    if not rows:
        return "_No rows._"
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(fmt(row[column]) for column in columns) + " |")
    return "\n".join(lines)


def write_outputs(
    output_dir: Path,
    rows: list[dict[str, Any]],
    args: argparse.Namespace,
    baseline_path: Path | None,
) -> None:
    summary = summarize(rows)
    comparison = build_comparison(rows, baseline_path)
    comparison_summary = summarize_comparison(comparison)

    write_csv(output_dir / "results.csv", rows)
    write_csv(output_dir / "summary.csv", summary)
    write_csv(output_dir / "comparison.csv", comparison)
    write_csv(output_dir / "comparison_summary.csv", comparison_summary)

    with (output_dir / "results.json").open("w", encoding="utf-8") as handle:
        json.dump(
            {
                "results": rows,
                "summary": summary,
                "comparison": comparison,
                "comparison_summary": comparison_summary,
                "baseline_path": str(baseline_path) if baseline_path else None,
            },
            handle,
            indent=2,
        )
    with (output_dir / "run_config.json").open("w", encoding="utf-8") as handle:
        json.dump(vars(args), handle, indent=2)

    with (output_dir / "results.md").open("w", encoding="utf-8") as handle:
        handle.write("# NYCTaxi Ungated Residual Correction Ablation\n\n")
        handle.write("## Per Seed\n\n")
        handle.write(
            markdown_table(
                rows,
                [
                    "seed",
                    "flow",
                    "residual_mae",
                    "residual_eee",
                    "base_mae",
                    "base_eee",
                    "event_prevalence",
                    "best_val_loss",
                    "best_val_epoch",
                ],
            )
        )
        handle.write("\n\n## Summary\n\n")
        handle.write(
            markdown_table(
                summary,
                [
                    "variant",
                    "flow",
                    "n",
                    "residual_mae_mean",
                    "residual_mae_std",
                    "residual_eee_mean",
                    "residual_eee_std",
                    "base_mae_mean",
                    "base_eee_mean",
                ],
            )
        )
        handle.write("\n\n## Comparison To Original Hyb-STEX\n\n")
        if baseline_path is not None:
            handle.write(f"Baseline: `{baseline_path}`\n\n")
        handle.write(
            markdown_table(
                comparison,
                [
                    "seed",
                    "flow",
                    "hybstex_soft_mae",
                    "ungated_residual_mae",
                    "delta_mae_ungated_minus_hybstex",
                    "hybstex_soft_eee",
                    "ungated_residual_eee",
                    "delta_eee_ungated_minus_hybstex",
                    "hybstex_f1_tuned",
                ],
            )
        )
        handle.write("\n\n## Comparison Summary\n\n")
        handle.write(
            markdown_table(
                comparison_summary,
                [
                    "flow",
                    "n",
                    "delta_mae_ungated_minus_hybstex_mean",
                    "delta_mae_ungated_minus_hybstex_std",
                    "delta_eee_ungated_minus_hybstex_mean",
                    "delta_eee_ungated_minus_hybstex_std",
                ],
            )
        )
        handle.write("\n")


def preflight_model(
    configs: dict[str, Any],
    data_dir: Path,
    device: str,
    event_percentile: float,
    event_threshold_source: str,
) -> None:
    from model.models import STSSL

    arrays = load_arrays(data_dir, event_percentile, event_threshold_source)
    args = build_run_args(configs, data_dir, seed=1, device=device, max_epochs=1)
    graph = load_graph(Path(args.graph_file), device)
    args.num_nodes = len(graph)
    model = STSSL(args).to(device)
    pred_params, classifier_params, bias_params = get_model_params_grouped(model)
    print("Preflight model constructed for ungated residual ablation.")
    print(f"NYCTaxi train x shape: {arrays['x_train'].shape}")
    print(f"NYCTaxi train y shape: {arrays['y_train'].shape}")
    print(f"NYCTaxi event threshold source: {event_threshold_source}")
    print(f"NYCTaxi train event prevalence: {arrays['evs_train'].mean():.6f}")
    print(f"NYCTaxi val event prevalence: {arrays['evs_val'].mean():.6f}")
    print(f"NYCTaxi test event prevalence: {arrays['evs_test'].mean():.6f}")
    print(f"Parameter groups: pred={len(pred_params)}, cls={len(classifier_params)}, bias={len(bias_params)}")
    del model, graph
    if device == "cuda":
        torch.cuda.empty_cache()


def main() -> int:
    root = repo_root()
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=str(root / "configs" / "NYCTaxi.yaml"))
    parser.add_argument("--data-dir", default=str(root / "preprocessed_data"))
    parser.add_argument("--output-dir", default=str(root / "nyctaxi_ungated_residual_results"))
    parser.add_argument("--seeds", default="1,2,3")
    parser.add_argument("--device", default="auto", choices=["auto", "cuda", "cpu"])
    parser.add_argument("--event-percentile", default=90.0, type=float)
    parser.add_argument(
        "--event-threshold-source",
        default="file",
        choices=EVENT_THRESHOLD_SOURCE_CHOICES,
        help=(
            "Event-label threshold source. 'file' uses saved evs_90 arrays; "
            "'train' regenerates paper-correct labels in memory; "
            "'split' reproduces the old notebook rule."
        ),
    )
    parser.add_argument("--max-epochs", default=None, type=int, help="Optional smoke-test epoch cap per phase.")
    parser.add_argument(
        "--baseline-results",
        default="auto",
        help="Path to previous drift experiment results.csv, 'auto', or 'none'.",
    )
    parser.add_argument("--preflight-only", action="store_true")
    args = parser.parse_args()

    data_dir = Path(args.data_dir).resolve()
    config_path = Path(args.config).resolve()
    device = args.device
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"

    preflight_environment(data_dir, device)
    add_repo_to_path(root)
    configs = load_config(config_path)
    preflight_model(configs, data_dir, device, args.event_percentile, args.event_threshold_source)
    if args.preflight_only:
        print("Preflight complete. No training was run.")
        return 0

    baseline_path: Path | None
    if args.baseline_results == "auto":
        baseline_path = find_latest_baseline(root)
    elif args.baseline_results.lower() == "none":
        baseline_path = None
    else:
        baseline_path = Path(args.baseline_results).resolve()
    if baseline_path is not None:
        print(f"Baseline comparison file: {baseline_path}")
    else:
        print("No baseline comparison file found/provided.")

    output_dir = Path(args.output_dir).resolve() / datetime.now().strftime("%Y%m%d-%H%M%S")
    output_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    for seed in parse_seed_list(args.seeds):
        print(f"\n=== NYCTaxi ungated_residual seed={seed} device={device} ===")
        run_rows = run_one(
            configs=configs,
            data_dir=data_dir,
            output_dir=output_dir,
            seed=seed,
            device=device,
            event_percentile=args.event_percentile,
            event_threshold_source=args.event_threshold_source,
            max_epochs=args.max_epochs,
        )
        rows.extend(run_rows)
        write_outputs(output_dir, rows, args, baseline_path)
        print(
            markdown_table(
                run_rows,
                ["seed", "flow", "residual_mae", "residual_eee", "base_mae", "base_eee"],
            )
        )

    write_outputs(output_dir, rows, args, baseline_path)
    print(f"\nSaved results to: {output_dir}")
    print((output_dir / "results.md").read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
